events {}

http {
	include /etc/nginx/mime.types;        # ← 加这行！！！
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
		server_name localhost;
		
		# 前端静态文件
		location / {
			root   /usr/share/nginx/html;
			index  index.html index.htm;
			# Vue Router history 模式必须加这一行
			try_files $uri $uri/ /index.html;
		}

        # Identity 服务
        location /api/identity/ {
            proxy_pass http://identity-api:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Merchant 服务
        location /api/merchant/ {
            proxy_pass http://merchant-api:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}