events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;

        # Identity 服务
        location /api/identity/ {
            proxy_pass http://identity-api:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Merchant 服务
        location /api/merchant/ {
            proxy_pass http://merchant-api:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 可选：前端静态文件（以后用）
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}