name: Build, Migrate and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Build Images
      run: |
        docker build -t merchant-api:${{ github.sha }} -f MerchantAdmin.API/Dockerfile .
        docker build -t identity-api:${{ github.sha }} -f Identity.API/Dockerfile .
        docker build -t merchant-admin-frontend:${{ github.sha }} -f MerchantAdmin.Frontend/Dockerfile .
        docker build -t db-migrator:${{ github.sha }} -f Dockerfile.migrate .



  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Update K8s manifests and Deploy
      shell: pwsh
      run: |
        (Get-Content k8s/07-merchant-api.yaml) -replace 'merchant-api:latest', 'merchant-api:${{ github.sha }}' | Set-Content k8s/07-merchant-api.yaml
        (Get-Content k8s/06-identity-api.yaml) -replace 'identity-api:latest', 'identity-api:${{ github.sha }}' | Set-Content k8s/06-identity-api.yaml
        (Get-Content k8s/08-merchantadmin.yaml) -replace 'merchant-admin-frontend:latest', 'merchant-admin-frontend:${{ github.sha }}' | Set-Content k8s/08-merchantadmin.yaml

        # 迁移
        kubectl apply -f k8s/identity-db-migrate-job.yaml
        kubectl apply -f k8s/merchant-db-migrate-job.yaml
        kubectl wait --for=condition=complete job/merchant-db-migrate -n merchant --timeout=60s
        kubectl wait --for=condition=complete job/identity-db-migrate -n merchant --timeout=60s
        
        # 3. 部署应用服务
        kubectl apply -f k8s/06-identity-api.yaml
        kubectl apply -f k8s/07-merchant-api.yaml
        kubectl apply -f k8s/08-merchantadmin.yaml
        kubectl wait --for=condition=ready pod -l app=identity-api -n merchant --timeout=120s
        kubectl wait --for=condition=ready pod -l app=merchant-api -n merchant --timeout=120s
        kubectl wait --for=condition=ready pod -l app=merchantadmin -n merchant --timeout=120s

        kubectl rollout restart deployment/merchant-api
        kubectl rollout restart deployment/identity-api
        kubectl rollout restart deployment/merchantadmin