<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MerchantAdmin.Shared.EventBus\MerchantAdmin.Shared.EventBus.csproj" />
    <ProjectReference Include="..\MerchantAdmin.Shared.EventBus.RabbitMQ\MerchantAdmin.Shared.EventBus.RabbitMQ.csproj" />
  </ItemGroup>

</Project>
